uploads = []
generated = []

[[outputs]]
id = "UTE9VJctG1xBpAKxfRXmK"
uri = "file://copyright-archive/app-cliente-copyright-20260401.tar.gz"
type = "unspecified"
title = "Archivio Copyright App Cliente - 01/04/2026"
