# Docker Compose per Gestionale Sanitario
# Alternativa semplificata per deployment con Docker

version: '3.8'

services:
  app:
    build: .
    container_name: gestionale-sanitario
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://gestionale_user:${DB_PASSWORD}@db:5432/gestionale_sanitario
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - gestionale-network

  db:
    image: postgres:15-alpine
    container_name: gestionale-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gestionale_sanitario
      - POSTGRES_USER=gestionale_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - gestionale-network
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: gestionale-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - gestionale-network

volumes:
  postgres_data:

networks:
  gestionale-network:
    driver: bridge